## 1. User Reviews (Đánh giá từ người dùng)

| Tên trường (Field) | Kiểu dữ liệu (Type) | Mô tả (Explanation) |
| :--- | :--- | :--- |
| **`rating`** | `float` | Điểm đánh giá sản phẩm (từ `1.0` đến `5.0`). |
| **`title`** | `str` | Tiêu đề của bài đánh giá. |
| **`text`** | `str` | Nội dung chi tiết của bài đánh giá. |
| **`images`** | `list` | Danh sách hình ảnh do người dùng đăng tải sau khi nhận hàng. Mỗi ảnh gồm nhiều kích thước khác nhau (`small_image_url`, `medium_image_url`, `large_image_url`). |
| **`asin`** | `str` | ID định danh duy nhất của phiên bản sản phẩm cụ thể. |
| **`parent_asin`** | `str` | ID gốc (Parent ID) của sản phẩm. *Lưu ý: Các sản phẩm khác màu, kiểu dáng, kích thước thường dùng chung một parent_asin. Hãy dùng ID này để liên kết với bảng Item Metadata.* |
| **`user_id`** | `str` | ID của người viết đánh giá. |
| **`timestamp`** | `int` | Thời gian đăng đánh giá (định dạng Unix timestamp). |
| **`verified_purchase`** | `bool` | Xác thực người dùng đã mua hàng thực tế hay chưa (`True`/`False`). |
| **`helpful_vote`** | `int` | Số lượt bình chọn "hữu ích" (helpful) từ những người dùng khác cho đánh giá này. |

---

## 2. Item Metadata (Thông tin chi tiết sản phẩm)

| Tên trường (Field) | Kiểu dữ liệu (Type) | Mô tả (Explanation) |
| :--- | :--- | :--- |
| **`main_category`** | `str` | Danh mục chính (ngành hàng/domain) của sản phẩm. |
| **`title`** | `str` | Tên đầy đủ của sản phẩm. |
| **`average_rating`** | `float` | Điểm đánh giá trung bình hiển thị trên trang sản phẩm. |
| **`rating_number`** | `int` | Tổng số lượt đánh giá của sản phẩm này. |
| **`features`** | `list` | Các tính năng nổi bật của sản phẩm (dưới dạng danh sách gạch đầu dòng). |
| **`description`** | `list` | Phần mô tả chi tiết về sản phẩm. |
| **`price`** | `float` | Giá bán của sản phẩm bằng USD (tại thời điểm thu thập dữ liệu). |
| **`images`** | `list` | Danh sách hình ảnh của sản phẩm. Mỗi ảnh có các kích thước khác nhau (`thumb`, `large`, `hi_res`). Trường `variant` biểu thị vị trí hiển thị của ảnh. |
| **`videos`** | `list` | Danh sách video liên quan đến sản phẩm (bao gồm tiêu đề và đường dẫn URL). |
| **`store`** | `str` | Tên của cửa hàng/thương hiệu bán sản phẩm. |
| **`categories`** | `list` | Danh mục phân cấp của sản phẩm (từ lớn đến nhỏ). |
| **`details`** | `dict` | Thông tin kỹ thuật chi tiết (chất liệu, thương hiệu, kích thước, v.v.) dưới dạng khóa-giá trị (key-value). |
| **`parent_asin`** | `str` | ID gốc (Parent ID) của sản phẩm (dùng để liên kết với bảng Reviews). |
| **`bought_together`** | `list` | Danh sách các gói sản phẩm được đề xuất mua cùng nhau từ website. |

In [1]:
import pandas as pd

reviews_file = '../data/Cell_Phones_and_Accessories.jsonl'
meta_file = '../data/meta_Cell_Phones_and_Accessories.jsonl'

In [2]:
first_chunk = True

meta_chunks = pd.read_json(meta_file, lines=True, chunksize=100000)

processed_chunks = []

for m_chunk in meta_chunks:
    m_chunk.drop(columns=['images', 'details', 'bought_together', 'videos', 'price', 'average_rating', 'rating_number', 'store', 'subtitle', 'author'], inplace=True)
    processed_chunks.append(m_chunk)

df_meta = pd.concat(processed_chunks, ignore_index=True)
df_meta

,main_category,title,features,description,categories,parent_asin
0,Cell Phones & Accessories,ARAREE Slim Diary Cell Phone Case for Samsung ...,"[Genuine Cow leather with 6 different colors, ...","[JUST LOOK, You can tell the difference. Make ...","[Cell Phones & Accessories, Cases, Holsters & ...",B013SK1JTY
1,Cell Phones & Accessories,Bastmei for OnePlus 7T Case Extremely Light Ul...,[Ultra-thin & Ultra-light: The ultra slim fit ...,[],"[Cell Phones & Accessories, Cases, Holsters & ...",B07ZPSG8P5
2,Cell Phones & Accessories,Wireless Fones Branded New Iphone 5C/LITE Hot ...,[],[],"[Cell Phones & Accessories, iPhone Accessories]",B00GKR3L12
3,Cell Phones & Accessories,"iPhone 6 Plus + Case, DandyCase Perfect PATTER...","[Slim-Fit design for the iPhone 6 Plus (5.5"" s...",[Case does not need to be removed for charging...,"[Cell Phones & Accessories, iPhone Accessories]",B00PB8U8BW
4,Cell Phones & Accessories,"Case for Galaxy S6/S6 Edge, Thin Translucent V...",[],[],"[Cell Phones & Accessories, Cases, Holsters & ...",B07D3RHSRV
...,...,...,...,...,...,...
1288485,None,Original White Touch Screen for Star N8000 Cel...,[],[],"[Cell Phones & Accessories, Cases, Holsters & ...",B00BHXX6N2
1288486,Cell Phones & Accessories,AERO ARMOR Protective Case for Samsung Galaxy ...,[],[],[],B00P9Y70XC
1288487,Sports & Outdoors,Bandiction 3 Pack Sport Band Compatible with A...,[],[],"[Cell Phones & Accessories, Accessories, Smart...",B08JCMWH7H
1288488,Cell Phones & Accessories,"Weycolor Moto E7 (2021) Case, Liquid Silicone ...",[],[],"[Cell Phones & Accessories, Cases, Holsters & ...",B08TQQRS69
1288489,Cell Phones & Accessories,Eagle Cell PDSAMT989D334 RingBling Brilliant D...,[The Silver Cross diamond design effectively g...,[The RingBling Silver Cross Diamond Case by Ea...,"[Cell Phones & Accessories, Cases, Holsters & ...",B007PMU4T8

In [3]:
first_chunk = True

review_chunks = pd.read_json(reviews_file, lines=True, chunksize=10000)

processed_chunks = []

for r_chunk in review_chunks:
    r_chunk.drop(columns=['images', 'verified_purchase', 'text', 'title', 'helpful_vote'], inplace=True)
    processed_chunks.append(r_chunk)
    if len(processed_chunks) >= 100:
        break

df_review = pd.concat(processed_chunks, ignore_index=True)
df_review

,rating,asin,parent_asin,user_id,timestamp
0,4,B08L6L3X1S,B08L6L3X1S,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2021-01-30 22:07:31.196
1,5,B079BPGF6C,B079BPGF6C,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2018-08-16 18:18:37.349
2,5,B088DR7Z5B,B0BBGGC8F2,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2021-08-17 21:21:44.798
3,4,B07XRDHDNQ,B07XRDHDNQ,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2020-05-26 05:14:42.910
4,5,B00A8ZDL9Y,B00A8ZDL9Y,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2014-08-25 19:23:08.000
...,...,...,...,...,...
999995,3,B00GGY8PAQ,B00GGY8PAQ,AH6G2UJ3CJ4PIO56IRAOF62GRWZQ,2014-12-27 22:07:45.000
999996,5,B07H11F2GG,B07H11F2GG,AHQGXL5L3VG6EBZFAQP4R6IPOTGQ,2019-08-18 03:14:36.662
999997,5,B01CY1CUB4,B01CY1CUB4,AHQGXL5L3VG6EBZFAQP4R6IPOTGQ,2016-06-16 04:42:14.000
999998,5,B00GJ36AZG,B00GJ36AZG,AE2P2I3OV4K2N23GSAZADUCJ3RLQ,2015-06-27 00:32:20.000
999999,5,B07Y5R57FS,B07Y5R57FS,AFCZS6XOPWG7XKUKP5U2VHCOE4LQ,2020-10-23 16:14:08.745

In [4]:
df_joined = pd.merge(df_review, df_meta, on='parent_asin', how='left')

df_joined['content'] = df_joined['features'].fillna('') + df_joined['description'].fillna('')

df_joined.drop(columns=['categories', 'features', 'description'], inplace=True)

df_joined

,rating,asin,parent_asin,user_id,timestamp,main_category,title,content
0,4,B08L6L3X1S,B08L6L3X1S,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2021-01-30 22:07:31.196,Cell Phones & Accessories,VUIIMEEK Square Case for iPhone 12 Pro Max 6.7...,[Specially designed for iPhone 12 Pro Max 2020...
1,5,B079BPGF6C,B079BPGF6C,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2018-08-16 18:18:37.349,All Electronics,"Fitian Fitbit Ionic Charging Cable, Replacemen...",[]
2,5,B088DR7Z5B,B0BBGGC8F2,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2021-08-17 21:21:44.798,Cell Phones & Accessories,Keytas Compatible with iPhone XR Screen Replac...,[【Easy Install】This LCD touch screen come with...
3,4,B07XRDHDNQ,B07XRDHDNQ,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2020-05-26 05:14:42.910,Amazon Home,TORRAS COOLIFY Zone 7 Midnight Green,[[Ultra-Thin yet Protective]: iPhone 11 pro sl...
4,5,B00A8ZDL9Y,B00A8ZDL9Y,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,2014-08-25 19:23:08.000,Cell Phones & Accessories,Gino Retro Style Paris Eiffel Tower Doodle Des...,"[Perfectly match with phone's shape and, make ..."
...,...,...,...,...,...,...,...,...
999995,3,B00GGY8PAQ,B00GGY8PAQ,AH6G2UJ3CJ4PIO56IRAOF62GRWZQ,2014-12-27 22:07:45.000,All Electronics,"Tech Armor Kindle Fire HDX Screen Protector, H...",[]
999996,5,B07H11F2GG,B07H11F2GG,AHQGXL5L3VG6EBZFAQP4R6IPOTGQ,2019-08-18 03:14:36.662,Cell Phones & Accessories,Osophter Compatible with Google Pixel 3 XL Sho...,[]
999997,5,B01CY1CUB4,B01CY1CUB4,AHQGXL5L3VG6EBZFAQP4R6IPOTGQ,2016-06-16 04:42:14.000,Cell Phones & Accessories,Sunnest 3 Pack 10FT Extra Long Nylon Braided M...,[Sunnest 3 Pack 10FT Extra Long Nylon Micro US...
999998,5,B00GJ36AZG,B00GJ36AZG,AE2P2I3OV4K2N23GSAZADUCJ3RLQ,2015-06-27 00:32:20.000,Cell Phones & Accessories,Arkon Friction Dash Phone Car Mount for iPhone...,[Apple iPhone X 8 7 6S Plus 8 7 6S and Samsung...
999999,5,B07Y5R57FS,B07Y5R57FS,AFCZS6XOPWG7XKUKP5U2VHCOE4LQ,2020-10-23 16:14:08.745,Cell Phones & Accessories,Tracfone Samsung Galaxy A10e 4G LTE Prepaid Sm...,[Long-Lasting Battery With a long-lasting batt...

In [5]:
df_joined.to_csv('preprocessed_data.csv',  index=False,  chunksize=50000)

print("Đã lưu file thành công!")

Đã lưu file thành công!